//! `RlmServer` constructor, accessors, and tool-router exposure.
//!
//! Sits in `mcp_helpers` (not `mcp`) because these are adapter-internal
//! infrastructure rather than command-handler endpoints. Keeping them
//! out of the `mcp` adapter layer is what lets `[architecture.call_parity]`
//! validate the actual tool methods in `server.rs` without flagging
//! the constructor or pure getters for "not delegating to application"
//! — which they correctly don't, because there's no business logic
//! to delegate.
//!
//! The constructor calls `RlmServer::tool_router()`, which is the
//! function generated by rmcp's `#[tool_router]` macro in `server.rs`.
//! That macro defaults to private visibility; we set
//! `vis = "pub(super)"` on the macro invocation so the function is
//! callable from this sibling module.

use std::path::PathBuf;
use std::sync::Arc;

use rmcp::handler::server::tool::ToolRouter;

use super::server::RlmServer;
use crate::output::Formatter;

impl RlmServer {
    /// Construct a new `RlmServer` rooted at `project_root` with the
    /// given output `formatter`. Builds the rmcp tool router once at
    /// construction time and shares it across `Clone`s of the server.
    #[must_use]
    pub fn new(project_root: PathBuf, formatter: Formatter) -> Self {
        Self {
            project_root,
            formatter,
            tool_router: Arc::new(Self::tool_router()),
        }
    }

    /// Project root path. Passed to each
    /// [`application::facades`](crate::application::facades) call so
    /// the facade can open a session anchored at the server's project
    /// root.
    pub(crate) fn project_root(&self) -> &PathBuf {
        &self.project_root
    }

    /// Access the rmcp tool router. Public for integration tests that
    /// dispatch tool calls without a transport.
    // qual:api
    pub fn get_tool_router(&self) -> &ToolRouter<Self> {
        &self.tool_router
    }
}
